baseURL = 'https://will-rosenberg.com/'
languageCode = 'en-us'
title = "Will Rosenberg"
theme = 'not-much'
copyright = 'mowteam Â© {year}'

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[markup]
   [markup.goldmark]
    [markup.goldmark.extensions]
      unsafe = false
      linkify = false
   [markup.highlight]
      style = "monokai"
      noClasses = true
      lineNos = false
      guessSyntax = true


[params]
theme = "dark"
palette = "eink"
showThemeNotice = true
showPostsSummary = true

# Navigation
[menu]
  [[menu.main]]
    identifier = "home"
    name = "home"
    title = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    identifier = "posts"
    name = "posts"
    title = "posts"
    url = "/posts"
    weight = 2

  [[menu.main]]
    identifier = "cv"
    name = "cv"
    title = "CV"
    url = "/cv.pdf"
    weight = 3
  
  [[menu.main]]
    identifier = "contact"
    name = "contact"
    title = "Contact"
    url = "/#Contact"
    weight = 4
